"""Diagnostics leaf layer for energy-guided ROI transport.

Diagnostics modules are frozen dataclasses plus pure evaluation functions:
structure/basin metrics, cone projection, high-water-mark teacher losses,
linear identifiability probes, spatial counterfactuals, step-strata analysis,
top-focused audits, decomposed actionability, and joint-probe validation.
They may depend on the stable method APIs in ``action``/``native``/``policy``/
``endpoint`` (boundary ADR rule 5), and they never write artifacts implicitly
— callers own persistence. Importing this package touches no CUDA and creates
no files (pinned by the import-safety gate in
``tests/contracts/test_energy_transport_import_boundaries.py`` and the
subprocess probe in ``tests/compatibility/test_energy_transport_flat_shims.py``).
"""

from spectral_detection_posttrain.methods.energy_transport.diagnostics.cone_projection import (
    ConeDecomposition,
    ConeProjectionEndpoint,
    EnergyFn,
    compute_class_prototypes,
    cone_dpog_regularizer,
    cone_residual_alignment_loss,
    cross_entropy_energy,
    decompose_cone_features,
    local_tangent_energy_endpoint,
    normalize_l2,
    project_to_tangent,
)
from spectral_detection_posttrain.methods.energy_transport.diagnostics.decomposed_actionability import (
    PairwiseRows,
    within_image_pairwise_rows,
    class_image_balanced_weights,
    sign_classification_metrics,
    ranked_abstention_metrics,
    calibrate_ranked_abstention,
    evaluate_decomposed_actionability_gates,
)
from spectral_detection_posttrain.methods.energy_transport.diagnostics.high_water_mark import (
    HighWaterMarkLossConfig,
    HighWaterMarkModuleSnapshot,
    should_update_high_water_mark,
    capture_high_water_mark_module,
    load_high_water_mark_module,
    ap75_boundary_weights,
    high_water_mark_action_loss,
    stop_high_water_mark_loss,
)
from spectral_detection_posttrain.methods.energy_transport.diagnostics.joint_probe_validation import (
    ConservativeCalibration,
    calibrate_conservative_threshold,
    calibrated_selection_metrics,
    constant_utility_baselines,
    imagewise_pairwise_accuracy,
    paired_bootstrap_mean_difference,
    shuffle_edge_topology,
)
from spectral_detection_posttrain.methods.energy_transport.diagnostics.linear_identifiability import (
    LocalCandidateRows,
    FrozenLocalFeatureMap,
    RidgeRegressor,
    extract_local_candidate_rows,
    move_local_candidate_rows,
    fit_local_feature_map,
    transform_local_candidate_rows,
    within_image_shuffle_order,
    image_balanced_weights,
    fit_ridge_regression,
    predict_ridge_regression,
    evaluate_identifiability_gates,
)
from spectral_detection_posttrain.methods.energy_transport.diagnostics.spatial_counterfactual import (
    SpatialCandidateRows,
    FrozenSpatialFeatureMap,
    extract_spatial_candidate_rows,
    move_spatial_candidate_rows,
    replace_action_features,
    spatial_counterfactual_blocks,
    spatial_layout_shuffle,
    within_image_delta_alignment_shuffle,
    fit_spatial_feature_map,
    transform_spatial_features,
    evaluate_spatial_counterfactual_gates,
)
from spectral_detection_posttrain.methods.energy_transport.diagnostics.step_strata import (
    StepActionRows,
    extract_step_action_rows,
    strata_masks,
    summarize_stratum,
    discover_stable_strata,
    select_primary_stratum,
    rate_matched_uniform_control,
    target_permutation_control,
    evaluate_step_strata_gates,
)
from spectral_detection_posttrain.methods.energy_transport.diagnostics.structure_metrics import (
    PrototypeBasinGeometry,
    ROIStructureSignature,
    ROIDualEnergy,
    roi_compactness_energy,
    roi_basin_energy,
    roi_basin_retention,
    centered_relation_matrix,
    relation_cka,
    inter_class_separation_energy,
    prototype_anchor_energy,
    inter_class_relation_energy,
    simplex_energy,
    class_topk_adjacency,
    graph_jaccard,
    basin_leakage_graph,
    prototype_basin_geometry,
    roi_structure_signature,
    roi_dual_energy,
)
from spectral_detection_posttrain.methods.energy_transport.diagnostics.top_focused_audit import (
    median_sign_metrics,
    top_focused_rank_metrics,
    evaluate_top_focused_gates,
)

__all__ = [
    "ConeDecomposition",
    "ConeProjectionEndpoint",
    "ConservativeCalibration",
    "EnergyFn",
    "FrozenLocalFeatureMap",
    "FrozenSpatialFeatureMap",
    "HighWaterMarkLossConfig",
    "HighWaterMarkModuleSnapshot",
    "LocalCandidateRows",
    "PairwiseRows",
    "PrototypeBasinGeometry",
    "ROIDualEnergy",
    "ROIStructureSignature",
    "RidgeRegressor",
    "SpatialCandidateRows",
    "StepActionRows",
    "ap75_boundary_weights",
    "basin_leakage_graph",
    "calibrate_conservative_threshold",
    "calibrate_ranked_abstention",
    "calibrated_selection_metrics",
    "capture_high_water_mark_module",
    "centered_relation_matrix",
    "class_image_balanced_weights",
    "class_topk_adjacency",
    "compute_class_prototypes",
    "cone_dpog_regularizer",
    "cone_residual_alignment_loss",
    "constant_utility_baselines",
    "cross_entropy_energy",
    "decompose_cone_features",
    "discover_stable_strata",
    "evaluate_decomposed_actionability_gates",
    "evaluate_identifiability_gates",
    "evaluate_spatial_counterfactual_gates",
    "evaluate_step_strata_gates",
    "evaluate_top_focused_gates",
    "extract_local_candidate_rows",
    "extract_spatial_candidate_rows",
    "extract_step_action_rows",
    "fit_local_feature_map",
    "fit_ridge_regression",
    "fit_spatial_feature_map",
    "graph_jaccard",
    "high_water_mark_action_loss",
    "image_balanced_weights",
    "imagewise_pairwise_accuracy",
    "inter_class_relation_energy",
    "inter_class_separation_energy",
    "load_high_water_mark_module",
    "local_tangent_energy_endpoint",
    "median_sign_metrics",
    "move_local_candidate_rows",
    "move_spatial_candidate_rows",
    "normalize_l2",
    "paired_bootstrap_mean_difference",
    "predict_ridge_regression",
    "project_to_tangent",
    "prototype_anchor_energy",
    "prototype_basin_geometry",
    "ranked_abstention_metrics",
    "rate_matched_uniform_control",
    "relation_cka",
    "replace_action_features",
    "roi_basin_energy",
    "roi_basin_retention",
    "roi_compactness_energy",
    "roi_dual_energy",
    "roi_structure_signature",
    "select_primary_stratum",
    "should_update_high_water_mark",
    "shuffle_edge_topology",
    "sign_classification_metrics",
    "simplex_energy",
    "spatial_counterfactual_blocks",
    "spatial_layout_shuffle",
    "stop_high_water_mark_loss",
    "strata_masks",
    "summarize_stratum",
    "target_permutation_control",
    "top_focused_rank_metrics",
    "transform_local_candidate_rows",
    "transform_spatial_features",
    "within_image_delta_alignment_shuffle",
    "within_image_pairwise_rows",
    "within_image_shuffle_order",
]
