"""Action-local energy-guided transport primitives for detector post-training.

This package is the maintained entry point for the new research line where the
class-conditioned target manifold is unknown.  It models ROI correction as a
small, constrained action rather than as direct prototype attraction.
"""

from spectral_detection_posttrain.methods.energy_transport.actions import (
    ActionLocalTransportHead,
    ROITransportActions,
    apply_bounded_score_delta,
    rescue_budget_loss,
    summarize_score_actions,
    threshold_preservation_loss,
    transport_action_energy,
)
from spectral_detection_posttrain.methods.energy_transport.benefit_energy import (
    ActionBenefitEnergyHead,
    ActionBenefitTargets,
    BenefitEnergyLossConfig,
    action_benefit_energy_loss,
    apply_action_benefit_gate,
    build_action_benefit_targets,
)
from spectral_detection_posttrain.methods.energy_transport.candidate_energy import (
    CandidateEnergyLossConfig,
    CandidateGainLossConfig,
    CandidateQualityTargets,
    ContextOnlyCandidateEnergyHead,
    SpatialCandidateEnergyHead,
    build_candidate_quality_targets,
    build_symmetric_box_candidates,
    candidate_action_energy_loss,
    candidate_action_gain_loss,
    select_min_energy_box_actions,
)
from spectral_detection_posttrain.methods.energy_transport.cone_projection import (
    ConeDecomposition,
    ConeProjectionEndpoint,
    compute_class_prototypes,
    cone_dpog_regularizer,
    cone_residual_alignment_loss,
    cross_entropy_energy,
    decompose_cone_features,
    local_tangent_energy_endpoint,
)
from spectral_detection_posttrain.methods.energy_transport.contracts import (
    ActionOutcome,
    ConstraintConfig,
    PreferenceBatch,
    ROIActionState,
)
from spectral_detection_posttrain.methods.energy_transport.geometric_constraints import (
    GeometricConstraintConfig,
    bbox_aware_action_loss,
    classify_error_modes,
    compute_action_local_prototypes,
    fg_bg_sep_action_loss,
    geometric_transport_loss,
    intra_tp_action_loss,
    loc_err_action_loss,
)
from spectral_detection_posttrain.methods.energy_transport.high_water_mark import (
    HighWaterMarkLossConfig,
    HighWaterMarkModuleSnapshot,
    ap75_boundary_weights,
    capture_high_water_mark_module,
    high_water_mark_action_loss,
    load_high_water_mark_module,
    should_update_high_water_mark,
    stop_high_water_mark_loss,
)
from spectral_detection_posttrain.methods.energy_transport.operators import (
    apply_box_delta,
    clip_boxes_to_image,
)
from spectral_detection_posttrain.methods.energy_transport.preferences import (
    build_top_bottom_preferences,
)
from spectral_detection_posttrain.methods.energy_transport.search import (
    ActionSearchConfig,
    ScoreActionSearchResult,
    apply_score_action_to_prediction,
    select_min_energy_score_actions,
)
from spectral_detection_posttrain.methods.energy_transport.structure_metrics import (
    PrototypeBasinGeometry,
    ROIDualEnergy,
    ROIStructureSignature,
    basin_leakage_graph,
    class_topk_adjacency,
    centered_relation_matrix,
    graph_jaccard,
    inter_class_relation_energy,
    inter_class_separation_energy,
    prototype_basin_geometry,
    prototype_anchor_energy,
    relation_cka,
    roi_basin_energy,
    roi_basin_retention,
    roi_compactness_energy,
    roi_dual_energy,
    roi_structure_signature,
    simplex_energy,
)

__all__ = [
    "ActionLocalTransportHead",
    "ActionBenefitEnergyHead",
    "ActionBenefitTargets",
    "ActionOutcome",
    "ActionSearchConfig",
    "ConeDecomposition",
    "ConeProjectionEndpoint",
    "ConstraintConfig",
    "BenefitEnergyLossConfig",
    "CandidateEnergyLossConfig",
    "CandidateGainLossConfig",
    "CandidateQualityTargets",
    "ContextOnlyCandidateEnergyHead",
    "SpatialCandidateEnergyHead",
    "GeometricConstraintConfig",
    "HighWaterMarkLossConfig",
    "HighWaterMarkModuleSnapshot",
    "PreferenceBatch",
    "PrototypeBasinGeometry",
    "ROIDualEnergy",
    "ROIActionState",
    "ROIStructureSignature",
    "ROITransportActions",
    "ScoreActionSearchResult",
    "apply_bounded_score_delta",
    "apply_action_benefit_gate",
    "apply_box_delta",
    "apply_score_action_to_prediction",
    "ap75_boundary_weights",
    "basin_leakage_graph",
    "build_top_bottom_preferences",
    "build_action_benefit_targets",
    "build_candidate_quality_targets",
    "build_symmetric_box_candidates",
    "capture_high_water_mark_module",
    "candidate_action_energy_loss",
    "candidate_action_gain_loss",
    "centered_relation_matrix",
    "class_topk_adjacency",
    "classify_error_modes",
    "clip_boxes_to_image",
    "compute_action_local_prototypes",
    "compute_class_prototypes",
    "cone_dpog_regularizer",
    "cone_residual_alignment_loss",
    "cross_entropy_energy",
    "decompose_cone_features",
    "fg_bg_sep_action_loss",
    "geometric_transport_loss",
    "graph_jaccard",
    "high_water_mark_action_loss",
    "intra_tp_action_loss",
    "inter_class_relation_energy",
    "inter_class_separation_energy",
    "local_tangent_energy_endpoint",
    "loc_err_action_loss",
    "load_high_water_mark_module",
    "bbox_aware_action_loss",
    "prototype_basin_geometry",
    "prototype_anchor_energy",
    "relation_cka",
    "roi_basin_energy",
    "roi_basin_retention",
    "roi_compactness_energy",
    "roi_dual_energy",
    "roi_structure_signature",
    "rescue_budget_loss",
    "select_min_energy_score_actions",
    "select_min_energy_box_actions",
    "should_update_high_water_mark",
    "simplex_energy",
    "stop_high_water_mark_loss",
    "summarize_score_actions",
    "threshold_preservation_loss",
    "transport_action_energy",
    "action_benefit_energy_loss",
]
