"""Segmentation method namespace for AFM/RLVR/DPO extensions."""

from spectral_detection_posttrain.methods.segmentation.eval_segmentation import (
    boundary_iou,
    eval_segmentation,
    mean_iou,
    per_class_iou,
    pixel_accuracy,
)
from spectral_detection_posttrain.methods.segmentation.manifold_afm import (
    ManifoldAFMBlock,
    ManifoldAFMStack,
)
from spectral_detection_posttrain.methods.segmentation.ot_segmentation_loss import (
    OTSegmentationLoss,
)
from spectral_detection_posttrain.methods.segmentation.signals import (
    PIXEL_CLASSIFICATION_SIGNALS,
    PixelSignalSpec,
    activation_centroid_consistency,
    aspect_ratio_plausibility,
    boundary_phase_coherence,
    boundary_reward,
    connected_component_reward,
    compute_amplitude_profile,
    compute_fft_amplitude,
    compute_lowfreq_phase_stats,
    compute_structure_similarity,
    dice_reward,
    fft,
    geometry,
    interior_exterior_texture_contrast,
    mask_iou_reward,
    multi_scale_saliency_consistency,
    nms_survivor_density,
    phase_correlation_score,
    pixel_classification,
    radial_amplitude_profile,
    score_edge_alignment,
    signal_by_id,
    signal_ids,
)

__all__ = [
    "PIXEL_CLASSIFICATION_SIGNALS",
    "PixelSignalSpec",
    "ManifoldAFMBlock",
    "ManifoldAFMStack",
    "OTSegmentationLoss",
    "activation_centroid_consistency",
    "aspect_ratio_plausibility",
    "boundary_iou",
    "boundary_phase_coherence",
    "boundary_reward",
    "connected_component_reward",
    "compute_amplitude_profile",
    "compute_fft_amplitude",
    "compute_lowfreq_phase_stats",
    "compute_structure_similarity",
    "dice_reward",
    "eval_segmentation",
    "fft",
    "geometry",
    "interior_exterior_texture_contrast",
    "mask_iou_reward",
    "mean_iou",
    "multi_scale_saliency_consistency",
    "nms_survivor_density",
    "per_class_iou",
    "phase_correlation_score",
    "pixel_accuracy",
    "pixel_classification",
    "radial_amplitude_profile",
    "score_edge_alignment",
    "signal_by_id",
    "signal_ids",
]
