"""Deterministic generator for the tracked research docs (refactor Task 8).

Regenerates the four tracked files under ``docs/research/``:

* ``README.md``           index of the research docs plus maintained prose
                          explaining how the registries govern status;
* ``current_status.md``   every research line with status, claim ceiling, and
                          decision document — status comes ONLY from
                          ``spectral_detection_posttrain/configs/registry/
                          research_lines.json``;
* ``experiment_index.md`` all experiment records grouped by record kind —
                          records come ONLY from ``experiments.json``;
* ``artifact_index.md``   metric rows from reviewed artifact manifests under
                          ``configs/registry/artifacts/`` ONLY. While the
                          directory holds no reviewed manifests the index
                          renders an explicit empty state instead of rows.

Determinism rules (enforced by
``tests/experiments/test_generated_research_docs.py``):

* sorted by stable IDs (research line id, experiment record id, manifest id);
* UTF-8, LF line endings, exactly one trailing newline;
* no timestamps — dates live in ``docs/research/refactor_ledger.md``;
* relative links only: link text shows the repo-relative path, the link
  target is relative to the generated file's own directory so it resolves
  both on disk and on the forge;
* every file starts with a visible generated-file header listing the
  generation inputs (registry file names plus their sha256 digests) so any
  drift is explainable.

CLI:

* ``python scripts/dev/generate_research_docs.py --write``  regenerate the
  four tracked files;
* ``python scripts/dev/generate_research_docs.py --check``  regenerate in
  memory and exit 1 on drift;
* ``--out-dir <dir>`` writes/compares against another directory (used by
  tests).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
REGISTRY_DIR_REPO = "spectral_detection_posttrain/configs/registry"
RESEARCH_LINES_REPO = f"{REGISTRY_DIR_REPO}/research_lines.json"
EXPERIMENTS_REPO = f"{REGISTRY_DIR_REPO}/experiments.json"
ARTIFACTS_DIR_REPO = f"{REGISTRY_DIR_REPO}/artifacts"
DOCS_DIR_REPO = "docs/research"
DEFAULT_DOCS_DIR = ROOT / "docs" / "research"
GENERATOR_REPO_PATH = "scripts/dev/generate_research_docs.py"
ARTIFACTS_MODULE_REPO = "spectral_detection_posttrain/experiments/artifacts.py"

GENERATED_FILE_NAMES = ("README.md", "current_status.md", "experiment_index.md", "artifact_index.md")

GENERATED_MARKER = (
    f"<!-- GENERATED by {GENERATOR_REPO_PATH} — do not edit by hand -->"
)

NO_REVIEWED_MANIFESTS_SENTENCE = "No reviewed artifact manifests exist yet."

_ACTIVE_STATUSES = ("active", "queued")
_MAIN_LINE_STATUSES = ("frozen", "blocked")

# Light structural validation for reviewed manifests rendered into
# artifact_index.md; the strict contract lives in
# ``spectral_detection_posttrain/experiments/artifacts.py`` and its tests.
_MANIFEST_REQUIRED_KEYS = (
    "manifest_kind",
    "manifest_id",
    "experiment_id",
    "completion",
    "evaluation_scope",
    "metrics_summary",
    "source_evidence_pointer",
)


# ---------------------------------------------------------------------------
# Inputs
# ---------------------------------------------------------------------------


def _sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _registry_dir(root: Path) -> Path:
    return root / "spectral_detection_posttrain" / "configs" / "registry"


def _load_research_lines(root: Path) -> list[dict]:
    payload = _load_json(_registry_dir(root) / "research_lines.json")
    return sorted(payload["lines"], key=lambda line: line["id"])


def _load_experiment_records(root: Path) -> list[dict]:
    payload = _load_json(_registry_dir(root) / "experiments.json")
    return sorted(payload["records"], key=lambda record: record["id"])


def _load_reviewed_manifests(root: Path) -> list[tuple[str, dict]]:
    """Return ``(repo_path, payload)`` pairs for reviewed manifests, sorted by id.

    A missing or empty artifacts directory is the expected initial state and
    yields an empty list. Manifest files that fail light structural
    validation raise: generation must fail loudly rather than silently skip
    or fabricate rows.
    """
    artifacts_dir = _registry_dir(root) / "artifacts"
    if not artifacts_dir.is_dir():
        return []
    manifests = []
    for path in sorted(artifacts_dir.glob("*.json")):
        payload = _load_json(path)
        if not isinstance(payload, dict):
            raise ValueError(f"artifact manifest must be a JSON object: {path}")
        missing = [key for key in _MANIFEST_REQUIRED_KEYS if key not in payload]
        if missing:
            raise ValueError(f"artifact manifest {path} is missing field(s): {missing}")
        if payload["manifest_kind"] != "reviewed":
            raise ValueError(
                f"only reviewed manifests may be indexed: {path} has "
                f"manifest_kind={payload['manifest_kind']!r}"
            )
        repo_path = f"{ARTIFACTS_DIR_REPO}/{path.name}"
        manifests.append((repo_path, payload))
    manifests.sort(key=lambda item: item[1]["manifest_id"])
    return manifests


def _input_lines(root: Path) -> list[str]:
    """Generation-input descriptors with sha256 digests for the header block."""
    registry = _registry_dir(root)
    lines = [
        f"{RESEARCH_LINES_REPO} sha256={_sha256_file(registry / 'research_lines.json')}",
        f"{EXPERIMENTS_REPO} sha256={_sha256_file(registry / 'experiments.json')}",
    ]
    manifests = _load_reviewed_manifests(root)
    if manifests:
        for repo_path, _payload in manifests:
            lines.append(f"{repo_path} sha256={_sha256_file(root / repo_path)}")
    else:
        lines.append(f"{ARTIFACTS_DIR_REPO}/ (no reviewed manifests)")
    return lines


def _header(root: Path) -> list[str]:
    lines = [GENERATED_MARKER, "<!-- generation inputs:"]
    lines.extend(f"     {entry}" for entry in _input_lines(root))
    lines.append("-->")
    return lines


# ---------------------------------------------------------------------------
# Rendering helpers
# ---------------------------------------------------------------------------


def _rel_link(doc_name: str, repo_path: str, root: Path) -> str:
    """Markdown link whose text is the repo-relative path and whose target is
    relative to the generated file's own directory (``docs/research/``)."""
    from_dir = (root / DOCS_DIR_REPO).resolve()
    target = os.path.relpath((root / repo_path).resolve(), start=from_dir)
    return f"[{repo_path}]({target.replace(os.sep, '/')})"


def _escape_cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def _code(text: str) -> str:
    return f"`{text}`"


def _format_scope(scope: dict) -> str:
    kind = str(scope.get("kind"))
    details = []
    if scope.get("image_count") is not None:
        details.append(f"{scope['image_count']} images")
    limits = []
    if scope.get("limit_train") is not None:
        limits.append(f"train {scope['limit_train']}")
    if scope.get("limit_val") is not None:
        limits.append(f"val {scope['limit_val']}")
    if limits:
        details.append(" / ".join(limits))
    if details:
        return f"{kind} ({'; '.join(details)})"
    return kind


def _finish(lines: list[str]) -> str:
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Document renderers
# ---------------------------------------------------------------------------


def _render_readme(root: Path, has_manifests: bool, manifest_count: int) -> str:
    artifact_state = (
        f"listing {manifest_count} reviewed artifact manifests"
        if has_manifests
        else "currently empty because no reviewed artifact manifests exist yet"
    )
    lines = [
        *_header(root),
        "",
        "# Research Documentation",
        "",
        "> Maintained prose: this file is generated deterministically by",
        f"> {_code(GENERATOR_REPO_PATH)}. The prose below lives in the",
        "> generator as constants; edit the generator, never this file.",
        "",
        "This directory holds the current research-state documentation for the",
        "repository. Everything here is derived from, or points at, the",
        f"registries under {_code(REGISTRY_DIR_REPO + '/')}.",
        "",
        "## Documents",
        "",
        "- [current_status.md](current_status.md) — research-line status, claim",
        "  ceilings, and decision documents, generated from the research status",
        "  registry.",
        "- [experiment_index.md](experiment_index.md) — all versioned experiment",
        "  records (executable definitions and historical artifacts), generated",
        "  from the experiment registry.",
        "- [artifact_index.md](artifact_index.md) — reviewed artifact manifests",
        f"  and their metric summaries; {artifact_state}.",
        "- [refactor_ledger.md](refactor_ledger.md) — hand-maintained ledger of",
        "  the repository research-state refactor; dates and commit history live",
        "  here, never in generated files.",
        "- [remote_gpu2_runbook.md](remote_gpu2_runbook.md) — guarded launch",
        "  procedure for the remote GPU2 host; companion to",
        "  `scripts/run/guard_gpu2.py`.",
        "",
        "## How The Registries Govern Status",
        "",
        f"- {_code(RESEARCH_LINES_REPO)} is the only machine-readable",
        "  authority for whether a research line is active, queued, paused,",
        "  frozen, blocked, diagnostic, baseline, historical, invalidated, or",
        "  validated. Prose documents never override it.",
        f"- {_code(EXPERIMENTS_REPO)} defines how versioned experiments can be",
        "  inspected or reproduced; it never implies scientific authorization.",
        f"- Reviewed artifact manifests under {_code(ARTIFACTS_DIR_REPO + '/')} are the",
        "  only source of metric rows in `artifact_index.md`; metrics must never",
        "  be hand-written into generated docs.",
        f"- {_code(REGISTRY_DIR_REPO + '/script_inventory.json')} inventories research",
        "  scripts; its heuristic classifications are proposals, not scientific",
        "  status.",
        "",
        "## Regeneration",
        "",
        "```bash",
        f"python {GENERATOR_REPO_PATH} --write   # regenerate the four files",
        f"python {GENERATOR_REPO_PATH} --check   # exit 1 on drift",
        "```",
        "",
        "Generated files contain no timestamps by design; for dates and commit",
        "history see [refactor_ledger.md](refactor_ledger.md).",
    ]
    return _finish(lines)


def _render_current_status(root: Path, lines_data: list[dict], records: list[dict]) -> str:
    active = [line for line in lines_data if line["status"] == "active"]
    queued = [line for line in lines_data if line["status"] == "queued"]
    active_ids = {line["id"] for line in active}
    authorized = [
        record
        for record in records
        if record["record_kind"] == "executable_definition"
        and record.get("runnable") == "authorized"
        and record["research_line"] in active_ids
    ]
    status_counts: dict[str, int] = {}
    for line in lines_data:
        status_counts[line["status"]] = status_counts.get(line["status"], 0) + 1
    counts_text = ", ".join(
        f"{status} {status_counts[status]}" for status in sorted(status_counts)
    )
    frozen_blocked = [
        line for line in lines_data if line["status"] in _MAIN_LINE_STATUSES
    ]

    out = [
        *_header(root),
        "",
        "# Current Research Status",
        "",
        "No experiment is currently authorized.",
        "",
        f"Status authority: {_code(RESEARCH_LINES_REPO)} (schema",
        "`research_lines.v1`). This page is regenerated from that registry; for",
        "decision dates see [refactor_ledger.md](refactor_ledger.md).",
        "",
        "## Authorization Summary",
        "",
        f"- Active lines: {len(active)}",
        f"- Queued lines: {len(queued)}",
        f"- Authorized experiments: {len(authorized)}",
        f"- Status counts ({len(lines_data)} lines): {counts_text}",
        "",
        "No line is active or queued, and no experiment record is authorized to",
        "run. Frozen-reproduction and diagnostic records exist for inspection",
        "only; dispatch requires a reviewed status transition committed to the",
        "registry first.",
        "",
        "## Frozen And Blocked Main Lines",
        "",
        "These main research lines are explicitly frozen or blocked; they must",
        "not be tuned, extended, or cited as current claims:",
        "",
    ]
    for line in frozen_blocked:
        out.append(f"- {_code(line['id'])} — {line['status']}")
    out.extend(
        [
            "",
            "## All Research Lines",
            "",
            "| Line ID | Status | Claim ceiling | Decision document |",
            "|---------|--------|---------------|-------------------|",
        ]
    )
    for line in lines_data:
        decision = line["decision_document"]
        decision_cell = _rel_link("current_status.md", decision, root) if decision else "—"
        out.append(
            "| "
            + " | ".join(
                (
                    _code(line["id"]),
                    line["status"],
                    _escape_cell(line["claim_ceiling"]),
                    decision_cell,
                )
            )
            + " |"
        )
    out.extend(
        [
            "",
            "Evidence pointers and notes for each line are recorded in the",
            f"registry itself ({_code(RESEARCH_LINES_REPO)}); this page renders",
            "only the status, claim ceiling, and decision document.",
        ]
    )
    return _finish(out)


def _render_experiment_index(root: Path, records: list[dict]) -> str:
    executable = [r for r in records if r["record_kind"] == "executable_definition"]
    historical = [r for r in records if r["record_kind"] == "historical_artifact"]
    out = [
        *_header(root),
        "",
        "# Experiment Index",
        "",
        f"Record authority: {_code(EXPERIMENTS_REPO)} (schema",
        f"`experiments.v1`). This index lists all {len(records)} records grouped",
        "by record kind. No record is authorized: runnable modes are limited to",
        "frozen reproduction or diagnostic use, and historical artifacts can",
        "never be dispatched.",
        "",
        f"## Executable Definitions ({len(executable)})",
        "",
        "| Experiment ID | Research line | Runnable | Handler | Scope | Config | Entrypoint |",
        "|---------------|---------------|----------|---------|-------|--------|------------|",
    ]
    for record in executable:
        out.append(
            "| "
            + " | ".join(
                (
                    _code(record["id"]),
                    _code(record["research_line"]),
                    _code(record["runnable"]),
                    _code(record["handler"]),
                    _format_scope(record["evaluation_scope"]),
                    _rel_link("experiment_index.md", record["config_path"], root),
                    _rel_link("experiment_index.md", record["legacy_entrypoint"], root),
                )
            )
            + " |"
        )
    out.extend(
        [
            "",
            f"## Historical Artifacts ({len(historical)})",
            "",
            "| Experiment ID | Research line | Evidence kind | Scope | Evidence pointer |",
            "|---------------|---------------|---------------|-------|------------------|",
        ]
    )
    for record in historical:
        out.append(
            "| "
            + " | ".join(
                (
                    _code(record["id"]),
                    _code(record["research_line"]),
                    _code(record["evidence_kind"]),
                    _format_scope(record["evaluation_scope"]),
                    _rel_link(
                        "experiment_index.md", record["source_evidence_pointer"], root
                    ),
                )
            )
            + " |"
        )
    return _finish(out)


def _render_artifact_index(root: Path, manifests: list[tuple[str, dict]], records: list[dict]) -> str:
    known_experiments = {record["id"] for record in records}
    out = [
        *_header(root),
        "",
        "# Artifact Index",
        "",
        "Metric rows in this index come only from reviewed artifact manifests",
        f"under {_code(ARTIFACTS_DIR_REPO + '/')}. A reviewed manifest is a tracked,",
        f"immutable snapshot created through the promotion path ({_code(ARTIFACTS_MODULE_REPO)});",
        "metric values must never be hand-written into this file.",
        "",
        "## Reviewed Artifact Manifests",
        "",
    ]
    if not manifests:
        out.extend(
            [
                f"{NO_REVIEWED_MANIFESTS_SENTENCE} The directory",
                f"{_code(ARTIFACTS_DIR_REPO + '/')} contains no manifests, so this index",
                "intentionally has no metric rows. Historical results remain in their",
                "original reports under `docs/reports/` until each family is backfilled",
                "through the reviewed-manifest promotion path.",
            ]
        )
        return _finish(out)
    out.extend(
        [
            "| Manifest ID | Experiment ID | Completion | Scope | Metrics summary | Source evidence |",
            "|-------------|---------------|------------|-------|-----------------|-----------------|",
        ]
    )
    for _repo_path, payload in manifests:
        experiment_id = payload["experiment_id"]
        if experiment_id not in known_experiments:
            raise ValueError(
                f"reviewed manifest {payload['manifest_id']!r} references unknown "
                f"experiment_id {experiment_id!r}"
            )
        metrics = payload.get("metrics_summary") or {}
        metrics_cell = (
            _code(json.dumps(metrics, sort_keys=True, separators=(",", ":")))
            if metrics
            else "—"
        )
        evidence = payload.get("source_evidence_pointer") or ""
        evidence_cell = _rel_link("artifact_index.md", evidence, root) if evidence else "—"
        out.append(
            "| "
            + " | ".join(
                (
                    _code(payload["manifest_id"]),
                    _code(experiment_id),
                    _code(payload["completion"]),
                    _format_scope(payload["evaluation_scope"]),
                    _escape_cell(metrics_cell),
                    evidence_cell,
                )
            )
            + " |"
        )
    return _finish(out)


# ---------------------------------------------------------------------------
# Public API and CLI
# ---------------------------------------------------------------------------


def generate_documents(root: Path = ROOT) -> dict[str, str]:
    """Return ``{file_name: content}`` for the four generated research docs."""
    root = Path(root)
    lines_data = _load_research_lines(root)
    records = _load_experiment_records(root)
    manifests = _load_reviewed_manifests(root)
    return {
        "README.md": _render_readme(root, bool(manifests), len(manifests)),
        "current_status.md": _render_current_status(root, lines_data, records),
        "experiment_index.md": _render_experiment_index(root, records),
        "artifact_index.md": _render_artifact_index(root, manifests, records),
    }


def write_documents(out_dir: Path, root: Path = ROOT) -> dict[str, str]:
    """Write the four generated docs into ``out_dir``; return the contents."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    docs = generate_documents(root=root)
    for name in GENERATED_FILE_NAMES:
        (out_dir / name).write_text(docs[name], encoding="utf-8", newline="\n")
    return docs


def check_drift(docs_dir: Path = DEFAULT_DOCS_DIR, root: Path = ROOT) -> tuple[bool, str]:
    """Compare tracked files against freshly generated content."""
    docs_dir = Path(docs_dir)
    docs = generate_documents(root=root)
    problems = []
    for name in GENERATED_FILE_NAMES:
        path = docs_dir / name
        if not path.is_file():
            problems.append(f"missing generated file: {name}")
            continue
        if path.read_text(encoding="utf-8") != docs[name]:
            problems.append(f"drift: {name}")
    if problems:
        return False, (
            "; ".join(problems)
            + f" — regenerate with `python {GENERATOR_REPO_PATH} --write`"
        )
    return True, "generated research docs are up to date"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="regenerate the four research docs")
    group.add_argument("--check", action="store_true", help="exit 1 when generated docs drift")
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="write/compare against this directory instead of docs/research/",
    )
    args = parser.parse_args(argv)

    docs_dir = args.out_dir if args.out_dir is not None else DEFAULT_DOCS_DIR
    if args.write:
        docs = write_documents(docs_dir)
        for name in GENERATED_FILE_NAMES:
            size = len(docs[name].encode("utf-8"))
            print(f"wrote {docs_dir / name} ({size} bytes)")
        return 0
    ok, message = check_drift(docs_dir=docs_dir)
    print(message)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
